name: async_loader
description: A flutter plugin for loading content asynchronously.
version: 0.1.2
author: Ryan Edge <ryan.c.edge@outlook.com>
homepage: https://github.com/chimon2000/async_loader

dependencies:
    flutter:
        sdk: flutter

environment:
    sdk: '>=2.12.0 <3.0.0'
